# Fichier pour tester les différentes fonctions utilisées dans mon script

In [1]:
import pandas as pd
import paths

def load_df(filepath="data/traiteur.csv"):
    print(f"File path : {filepath}")
    try:
        # On essaie d'accéder à la variable 'location_path' dans le module 'paths'
        file_path = filepath

        # Lecture du fichier CSV
        df_location = pd.read_csv(file_path)

    except AttributeError:
        print("Le chemin du fichier est introuvable.")
    except FileNotFoundError:
        print("Le fichier spécifié est introuvable.")
    return df_location

In [2]:

df = load_df()
df.head(5)

File path : data/traiteur.csv

,Name,Address_full,Phone_number,Website,Rating,Region,Category
0,Code-Cuisine Le Traiteur Grand-Est,"58 Rue du Bearn, 54400 Cosnes-et-Romain, France",+33 3 57 10 01 14,http://www.code-cuisine.com/,4.9,Grand Est,NaN
1,Traiteur LH Créations - Sainte-Marie-aux-Chênes,NaN,+33 6 14 36 75 82,http://www.lhcreations.fr/,4.9,Grand Est,NaN
2,Sissi traiteur gourmandise,NaN,+33 6 32 50 71 70,https://www.facebook.com/profile.php?id=100076...,5.0,Grand Est,NaN
3,Un Chef à la maison ! David Ciré TRAITEUR,"3 Impasse De Hayes, 57640 Vry, France",+33 6 10 11 75 51,http://www.unchefalamaison.fr/,4.9,Grand Est,NaN
4,Espace Traiteur,"8 Rue Émile Gallé, 54940 Belleville, France",+33 6 13 66 88 56,https://espace-traiteur.eatbu.com/?lang=fr,4.9,Grand Est,NaN

In [8]:
df.columns = df.iloc[0]
df = df[1:].reset_index(drop=True)
df.head()

,Code-Cuisine Le Traiteur Grand-Est,"58 Rue du Bearn, 54400 Cosnes-et-Romain, France",+33 3 57 10 01 14,http://www.code-cuisine.com/,4.9,Grand Est,NaN
0,Traiteur LH Créations - Sainte-Marie-aux-Chênes,NaN,+33 6 14 36 75 82,http://www.lhcreations.fr/,4.9,Grand Est,NaN
1,Sissi traiteur gourmandise,NaN,+33 6 32 50 71 70,https://www.facebook.com/profile.php?id=100076...,5.0,Grand Est,NaN
2,Un Chef à la maison ! David Ciré TRAITEUR,"3 Impasse De Hayes, 57640 Vry, France",+33 6 10 11 75 51,http://www.unchefalamaison.fr/,4.9,Grand Est,NaN
3,Espace Traiteur,"8 Rue Émile Gallé, 54940 Belleville, France",+33 6 13 66 88 56,https://espace-traiteur.eatbu.com/?lang=fr,4.9,Grand Est,NaN
4,le Traiteur Pierre Mayer et Nisse,"3 Pl. du Marché au Blé, 57220 Boulay-Moselle, ...",+33 7 82 15 33 00,https://www.traiteurpierremayer.fr/,4.9,Grand Est,NaN

In [3]:
df.isna().mean()

Name            0.000400
Address_full    0.372353
Phone_number    0.034758
Website         0.206153
Rating          0.111866
Region          0.000400
Category        0.493408
dtype: float64

In [5]:
df.columns = df.columns.str.lower()
df.head()

,name,address_full,phone_number,website,rating,region,category
0,Code-Cuisine Le Traiteur Grand-Est,"58 Rue du Bearn, 54400 Cosnes-et-Romain, France",+33 3 57 10 01 14,http://www.code-cuisine.com/,4.9,Grand Est,NaN
1,Traiteur LH Créations - Sainte-Marie-aux-Chênes,NaN,+33 6 14 36 75 82,http://www.lhcreations.fr/,4.9,Grand Est,NaN
2,Sissi traiteur gourmandise,NaN,+33 6 32 50 71 70,https://www.facebook.com/profile.php?id=100076...,5.0,Grand Est,NaN
3,Un Chef à la maison ! David Ciré TRAITEUR,"3 Impasse De Hayes, 57640 Vry, France",+33 6 10 11 75 51,http://www.unchefalamaison.fr/,4.9,Grand Est,NaN
4,Espace Traiteur,"8 Rue Émile Gallé, 54940 Belleville, France",+33 6 13 66 88 56,https://espace-traiteur.eatbu.com/?lang=fr,4.9,Grand Est,NaN

In [7]:
selected_columns = ['name', 'address_full', 'phone_number', 'rating']
#selected_columns = ['name'.upper(), 'address_full'.upper(), 'phone_number'.upper(), 'rating'.upper()]
new_df = df[selected_columns]
new_df.isna().mean()

name            0.000400
address_full    0.372353
phone_number    0.034758
rating          0.111866
dtype: float64

In [8]:
new_df = new_df.dropna()

In [9]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1480 entries, 0 to 2502
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          1480 non-null   object
 1   address_full  1480 non-null   object
 2   phone_number  1480 non-null   object
 3   rating        1480 non-null   object
dtypes: object(4)
memory usage: 57.8+ KB

In [10]:
new_df.isna().mean()

name            0.0
address_full    0.0
phone_number    0.0
rating          0.0
dtype: float64

In [11]:
new_df.isnull().mean()

name            0.0
address_full    0.0
phone_number    0.0
rating          0.0
dtype: float64

In [12]:
from geopy.geocoders import Nominatim
def get_coordinates(address):
    geolocator = Nominatim(user_agent="geo_converter")
    location = geolocator.geocode(address)

    if location:
        return location.latitude, location.longitude
    else:
        return None

In [12]:
get_coordinates('rue du pont des landes  78310 coignières  france')

(48.7373765711654, 1.9090951268328515)

In [12]:
# save new_df
new_df.to_csv('new_df.csv', index=False)

In [13]:
new_df.head(10)

,name,address_full,phone_number,rating
0,Code-Cuisine Le Traiteur Grand-Est,"58 Rue du Bearn, 54400 Cosnes-et-Romain, France",+33 3 57 10 01 14,4.9
3,Un Chef à la maison ! David Ciré TRAITEUR,"3 Impasse De Hayes, 57640 Vry, France",+33 6 10 11 75 51,4.9
4,Espace Traiteur,"8 Rue Émile Gallé, 54940 Belleville, France",+33 6 13 66 88 56,4.9
5,le Traiteur Pierre Mayer et Nisse,"3 Pl. du Marché au Blé, 57220 Boulay-Moselle, ...",+33 7 82 15 33 00,4.9
10,Le Relais Gourmand,"13 Rue de la Moselotte, 54520 Laxou, France",+33 3 83 21 79 53,4.8
11,Sur-Mesure By Vincent Vervisch | Chef À Domici...,"3 Rte de Neuhof, 67400 Illkirch-Graffenstaden,...",+33 6 31 35 47 18,5.0
12,MikaZ,"3 Rue des Vosges, 57400 Buhl-Lorraine, France",+33 6 77 17 31 37,4.8
13,Les Gentlemen's évents Traiteur,"15 Rue du Stade, 88560 Saint-Maurice-sur-Mosel...",+33 7 66 68 36 97,4.4
14,Arpèges et Saveurs Gourmandes du Grand-Est,"Imp. de l'Estournel, 54170 Allain, France",+33 6 12 91 53 21,3.8
15,Vernois Traiteur,"32 Rue nationale, 57420 Verny, France",+33 3 87 52 41 42,4.7

In [14]:
list_address = new_df['address_full'].tolist()
count = 0
_list = []
for address in list_address:
    add = address.rstrip().split(',')

    if len(add) > 3:
        count += 1
        _list.append(add)

In [15]:
for element in _list:
    print(element)

['Le Manoir des Cygnes', ' 150 Les Berges de Seine', ' 91830 Le Coudray-Montceaux', ' France']
['Espace Venise', ' 30 Rte de Groslay', ' 95200 Sarcelles', ' France']
['Glassy Events', ' Rue du Pont des Landes', ' 78310 Coignières', ' France']
['Salle de réception Le Vendome', ' 5 Rue des Chardonnerets', ' 93290 Tremblay-en-France', ' France']
['Farm Petite Loge', ' La Petite Loge', ' 77580 La Haute-Maison', ' France']
['Espace Eden | Salle de Réception 77 | Salle de réception seine et marne', " 2 Rue de l'Industrie", ' 77270 Villeparisis', ' France']
['Chateau de Serans', ' 60 Grande Rue', ' 60240 Serans', ' France']
['Priory of Saint Cyr', ' 18 Le Ru de Vrou', ' 77750 Saint-Cyr-sur-Morin', ' France']
['ESPACE LANGEVIN', ' 5 bis Ave. Paul Langevin', ' 95220 Herblay-sur-Seine', ' France']
['Domaine La Bastide', ' 80 Rue Pierre Curie', ' 95540 Méry-sur-Oise', ' France']
['Clos du Moulin Neuf', ' Le Moulin Neuf', ' 78660 Saint-Martin-de-Bréthencourt', ' France']
['Espace Royal - Salles de Reception', ' Métro', ' Saint Mandé FR', ' 6 Rue de Valmy', ' 93100 Montreuil', ' France']
['factory 58', ' 12 Rue Gutenberg', ' 93000 Bobigny', ' France']
['Palais Groupe Salle de Mariage 91', ' 2 Rue Jules Guesde', ' 91130 Ris-Orangis', ' France']
['Domaine de la Butte Ronde', ' La Butte Ronde', ' 78125 La Boissière-École', ' France']
['La Ferme Du Parc', ' 1 Gr Grande Rue', ' 91410 Chatignonville', ' France']
['Castle Vaugrigneuse', ' 11 Rue Héroard', ' 91640 Vaugrigneuse', ' France']
['La Verrière 91', ' 3 Rue Marie Marvingt', ' 91700 Fleury-Mérogis', ' France']
["LE CLOS DE L'ORANGERIE", ' Chemin de Malassis', ' 78710 Rosny-sur-Seine', ' France']
['Domaine du Chateau Verderonne', ' 7b Rue du Château', ' 60140 Verderonne', ' France']
['Reception room THE TULIPS', ' 8 Rue des Bâtisseurs', ' 91560 Crosne', ' France']
['Le Carré Marne', ' 27 Quai de Bonneuil', ' 94100 Saint-Maur-des-Fossés', ' France']
['RITZ PLAZZA', ' 43 Rue Saint-André', ' 93000 Bobigny', ' France']
['Manoir De La Chapelle Room Receptions Hotel', ' 1 Rte de Sainte-Colombe', ' 27950 La', ' France']
['Le Clos du Colombier', ' Ferme de Malassise', ' 77610 Fontenay-Trésigny', ' France']
['La Bastie de la Jonchère', ' La Jonchère', ' 26300 Beauregard-Baret', ' France']
['Field La Fauconnière', ' La Fauconnière', ' 77820 Les Écrennes', ' France']
['Château de Saint-Martin-du-Tertre', ' Allée de la Fontaine au Roy', ' 95270', ' 95270 Saint-Martin-du-Tertre', ' France']
['The Golden Edge', ' 27 Rte de Dourdan', ' 78730 Sainte-Mesme', ' France']
['Orangerie du Manoir des Vignes', ' 58 Rue Bernard', ' 93000 Bobigny', ' France']
['Le Joyau de la Marne', ' 1 Av. de Rigny', ' 94360 Bry-sur-Marne', ' France']
['La Bella - Wedding Room', ' Reception', ' 16 Rue de Pontault', ' 77680 Roissy-en-Brie', ' France']
["Le palmier d'or 77 - Location salle de réception mariage traiteur à domicile SEINE-ET-MARNE 77", ' 5 Rue Saint-Claude', ' 77340 Pontault-Combault', ' France']
['Estate Brunel', ' 22 sente jean brunel', ' 95510 Aincourt', ' France']
['Area Des Clos Vallées Salle De Réceptions', ' 7 Rue de la Croisette', ' 78980 Longnes', ' France']
['Domaine de Champigny - Salle de Réception', ' Le Domaine de Champigny', ' RN 36', ' 77390 Crisenoy', ' France']
['Villiers Palace mariage', ' 12 Av. des Entrepreneurs', ' 95400 Villiers-le-Bel', ' France']
["Loca'Salle", ' 6 Rue de la Palombe', ' 95610 Éragny', ' France']
['Au Jardin Des Saules', ' 48 Rue du Vieux Chemin de Saint-Germain', ' 95100 Argenteuil', ' France']
['Palais 77 | Salle de Mariage', ' 2 Rue des Argiles Vertes', ' 77130 Saint-Germain-Laval', ' France']
['Salle de réception Espace La Palombe', ' 7 Rue de la Palombe', ' 95610 Éragny', ' France']
['La Ferme du Roy', ' 4 Grande Rue', ' 60540 Bornel', ' France']
['Ferme Du Prieuré', ' rue de Villepreux', ' 78590 Rennemoulin', ' France']
['Salle de Réception Mariage Rhône Alpes - Le Château du Sou', ' Château du Sou', ' 1539 Rte du Morgon', ' 69640 Lacenas', ' France']
['Domaine des Coccinelles', ' La Tuilerie', ' 91470 Angervilliers', ' France']
['LOKUS l SALLE DE RECEPTIONS 77', ' 2000 Rue Denis Papin', ' 77550 Réau', ' France']
['Area Du Colombier', ' 1', ' Grande Rue Route départementale 981 Beauvais Gisors', ' 60155 Saint-Léger-en-Bray', ' France']
['Salle de réception La Scène', ' 6 Chem. du Bout Large', ' 78540 Vernouillet', ' France']
['The Lyna Shows', ' 23 Rue Léon Geffroy Bat D2', ' 94400 Vitry-sur-Seine', ' France']
['Le palacio', ' 15 Rue Camille Flammarion', ' 91630 Avrainville', ' France']
['Domaine de la Nacelle', ' 63 Grande Rue', ' 60620 Rosoy-en-Multien', ' France']
['La Princess Réception', ' 35 RD 306', ' 77240 Vert-Saint-Denis', ' France']
["Salle LUNE D'OR", ' 20 Av. des Courtes Epluches', ' 91100 Villabé', ' France']
['Le Pavillon de la Marne', ' 2 Av. du Baron Louis', ' 93160 Noisy-le-Grand', ' France']
['Château La Hitte', " Château La Hitte 973 route d'Agen", ' 47230 Lavardac', ' France']
['Ferme de Beauvais', ' La Ferme de Beauvais', ' 91150 Morigny-Champigny', ' France']
['Domaine De La Vallée Aux Pages', ' 02 Rue de la Vallée', ' 78660 Paray-Douaville', ' France']
['Pavillon Royal', ' Carrefour du bout des lacs', ' 1 Rte de la Muette à Neuilly', ' 75116 Paris', ' France']
['Area Two Tours', ' 5201 N20', ' 91150 Morigny-Champigny', ' France']
['Salle Mélodie', ' 5 Av. de la Résistance', ' 93240 Stains', ' France']
['LA GRANGE DU MESNIL VARIN', ' 204 Le Mesnil Varin', ' 76480 Saint-Paër', ' France']
['Victoria Park', ' 5 bis Bd des Astronautes', ' 93160 Noisy-le-Grand', ' France']
['Ferme du silo - Location de salle réception (Seine et Marne)', ' route de', ' La Bourgognerie', ' 77220 Tournan-en-Brie', ' France']
['La Ferme du Bois aux Dames - Salle de reception 77', ' Ferme du bois aux dames', ' 77650 Soisy-Bouy', ' France']
['Manoir Foulons', ' 1 Chem. des Foulons', ' 78790 Rosay', ' France']
['Location de salle', ' salle de mariage', ' Royal Riaz 77', ' 15 All. Jean Image', ' 77200 Torcy', ' France']
['Area Du Marais', ' 13 Chem. du Marais', ' 91720 Maisse', ' France']
['La Grange des Mollières', ' Chem. des Molières', ' 78270 La Villeneuve-en-Chevrie', ' France']
['La Bella Vita', ' 3 Pl. Jules Froelinger', ' 91200 Athis-Mons', ' France']
['Cristal 91', ' 14 Rue Gustave Madiot', ' 91070 Bondoufle', ' France']
['Moulin de Moulignon', ' Moulin De Moulignon', ' 77410 Messy', ' France']
['La Rose 77 | Événementiel (77)', ' 43 Route Nationale 7 lieu dit ferme de la folie', ' 77310', ' 77310 Boissise-le-Roi', ' France']
['Le Manoir Du Thil', ' 25 Rue Pierre Langlois', ' 27150 Le Thil', ' France']
['Domaine de la Muette', ' Lormeteau RD35 route de beauvais', ' 60240', ' France']
['Ferme du Genièvre', ' 25 Rue de la Libération', ' 78660 Prunay-en-Yvelines', ' France']
['FOREST FARM', ' Forest', ' 1 Grande Rue', ' 77390 Chaumes-en-Brie', ' France']
['Château de Lésigny', ' Rue de la Croix', ' 77150 Lésigny', ' France']
['The Royal Wedding', ' 45 Rue des Entrepreneurs', ' 78420 Carrières-sur-Seine', ' France']
['THE ROOM FAUVETTES', ' 12 Rue de Paris', ' 95330 Domont', ' France']
['The Fiesta & Privilege - Receptions', ' 2 All. de Dublin', ' 93320 Les Pavillons-sous-Bois', ' France']
['Domaine Les Aulnois - Salle de réception', ' Rue des Champs', ' 77120 Beautheil-Saints', ' France']
['La Bella Argenteuil', ' 17 Rue Jean-Pierre Timbaud', ' 95100 Argenteuil', ' France']
['Elysée Mariage', ' ZAC La Villette-Aux-Aulnes', ' 3 Rue Galilée', ' 77290 Mitry-Mory', ' France']
['Espace Alliance', ' 5 Rue Galilée Bât 2', ' 93150 Le Blanc-Mesnil', ' France']
['La Scena', ' 8 Av. Henri Barbusse', ' 93000 Bobigny', ' France']
['Royal Plaza', ' 223 Rue La Fontaine', ' 94120 Fontenay-sous-Bois', ' France']
['Golden House Salle des Fêtes', ' 195 Rte de Saint-Leu', ' 93800 Épinay-sur-Seine', ' France']
['Salle De Récéption Ile De France -La Grand Maison- Salle Mariage-Location De Salle Ile De France', ' La Grand-Maison', ' 77370 Vanvillé', ' France']
['MOULIN VERT - Salles de Réception en Bords de Marne - Traiteur', ' 103 Chem. de Contre Halage', ' 94500 Champigny-sur-Marne', ' France']
['Le Château bombon location de salles', ' mariage', ' traiteur pour mariage mixte', 'anniversaires', ' Le Château de Bombon', ' 77720 Bombon', ' France']
['Location salle 91 - Bondoufle Réception - Palace Event', ' 2 Rue des Bordes', ' 91070 Bondoufle', ' France']
['The Garden of Passions', ' 902 D8N', ' 13780 Cuges-les-Pins', ' France']
['Le Jardin D’alya', ' 11 Rue du Bosquet', ' 60570 Mortefontaine-en-Thelle', ' France']
['Château Mariage Oise "Domaine de Sainte Claire"', ' 40 Rue de Sainte-Claire', ' 60350 Berneuil-sur-Aisne', ' France']
["Mary d'Arvigny", ' All. Edouard Branly', ' 77550 Moissy-Cramayel', ' France']
['La ferme de Vintué', ' 12 Rue des Chênes Rouges', ' 91580 Étréchy', ' France']
['Le Château de Nans', ' D560', ' 83860 Nans-les-Pins', ' France']
['Domaine de la Grangette', ' route de Villeveyrac', ' 34530 Montagnac', ' France']
['La Girafe paris réceptions', ' 154 Av. Gallieni', ' 93170 Bagnolet', ' France']
['Castle Santeny', ' 2 Rte de Marolles', ' 94440 Santeny', ' France']
['Le Manège de Saint Cloud', ' 121bis Rue du Lieutenant Colonel de Montbrison', ' 92500 Rueil-Malmaison', ' France']
['Espace Noisy Le Sec', ' 14 Rue de la Pointe', ' 93130 Noisy-le-Sec', ' France']
["Chateau d'Amécourt:Séminaire réunion salle mariage réception location château gite de groupe Eure", ' 2 Rue du Buisson de Bleu', ' 27140 Amécourt', ' France']
["Le Domaine d'Euclide", ' 42 Rue de Châtres', ' 91790 Boissy-sous-Saint-Yon', ' France']
['Orchidée', ' 2 Rue Alexis de Tocqueville', ' 92160 Antony', ' France']
['The Domaine de Collen', ' Chemin de Collen', ' 62170 Lépine', ' France']
['château de Saint Offenge - Mariages', ' Séminaires', " Maison d'Hôtes", ' 50 Rte Sainte-Euphémie', ' 73100 Saint-Offenge', ' France']
['Château Bouffémont', ' 8 Rue Léon Giraudeau', ' 95570 Bouffémont', ' France']
['Field La Mazure', ' La Fringale', ' La Masure', ' 77640 Jouarre', ' France']
['Manoir De Randrecard', ' Randrecard', ' 56250 Treffléan', ' France']
['Les Salons Emirates', ' 146 Rue Léon Geffroy', ' 94400 Vitry-sur-Seine', ' France']
['Area Des Bayettes', ' 10 Rte nationale', ' 78980 Mondreville', ' France']
['Les Salons Beauchamp', ' 3 Rue Denis Papin', ' 95250 Beauchamp', ' France']
['Le Paradise 77 | salle de réception 77 | salle de mariage Meaux 77', ' 5 Av. Fridingen', ' 77100 Nanteuil-lès-Meaux', ' France']
['Field The Edge Of The Bois', ' D113', ' 78710 Rosny-sur-Seine', ' France']
['Chateau de Plumasserie', ' Rte de Bellefontaine', ' 77610 Fontenay-Trésigny', ' France']
['Domaine de La Réthorée', ' 26 ter La Rethoree', ' 77120 Giremoutiers', ' France']
['Area Du Bois Saint Mard', ' 11 Rue du Maréchal Leclerc', ' 60170 Tracy-le-Val', ' France']
['Domaine Saint-Pierre', ' Frm de Saint-Pierre', ' 77890 Gironville', ' France']
['Salons Varenne', ' 44 Rue Paul Lafargue', ' 93160 Noisy-le-Grand', ' France']
['La Méridienne', ' 3 BIS Rue du Pont de Baillet', ' 95560 Montsoult', ' France']
['The Manor of My Father', ' Frm de la Glazière', ' 77820 Les Écrennes', ' France']
['Le domaine du Ruisseau', ' 896 za', ' La Tuilière', ' 69510 Thurins', ' France']
['Salle Le Diamant', ' 7 Rue Charles François Daubigny', ' 95870 Bezons', ' France']
['Le Colombier du Manoir', ' lieu-dit', ' 6 route de Teurteville', ' Le Manoir', ' 14710 Mandeville-en-Bessin', ' France']
["L'étincelle", ' 61 ZA les Quatre Vents', " 95650 Boissy-l'Aillerie", ' France']
['La Closerie de Montgermont', ' 16 Rue de Montgermont', ' 77310 Pringy', ' France']
['The Orangerie Vatimesnil', ' 6 Rue du Château hameau de vatimesnil', ' 27150 Sainte-Marie-de-Vatimesnil', ' France']
['Le Saphir', ' 47 Rte de Goussainville', ' 95190 Fontenay-en-Parisis', ' France']
['Salon La Belle Alliance', ' 5 Rue Charles Michels', ' 95100 Argenteuil', ' France']
['Manoir de Tigeaux', ' 60 D20', ' 77163 Tigeaux', ' France']
['domaine des 3 voyages', ' 7 Rue de Pacy', ' 27640 Merey', ' France']
['Sen Sabai Salle de Réception', ' 6 bis Rue de la Noue Guimante', ' 77400 Saint-Thibault-des-Vignes', ' France']
['Les Salons Hoche', ' 9 Av. Hoche', ' 75008 Paris', ' France']
['The Marolles Garden', ' 2 Rue du Vallon', ' 94440 Marolles-en-Brie', ' France']
['Domaine du Petit Varennes', ' 62 Rue du Mal Leclerc', ' 89140 Serbonnes', ' France']
['Salle Neila Maya', ' 43 Rue Léon Jouhaux', ' 78500 Sartrouville', ' France']
['Le Corps de Garde: location salle de réception', ' mariages', ' séminaire', ' cérémonie laïque (Oise 60)', ' 4 Rue Driard', ' 60530 Neuilly-en-Thelle', ' France']
['Salle de réception/mariage/Mauperthuis Event', ' Frm de Mauperthuis', ' 77130 Forges', ' France']
['Salle de Réception Matecaña', ' 211-213', ' Rue Paul et Camille Thomoux', ' 93330 Neuilly-sur-Marne', ' France']
['le Moulin de Mourette', ' 88 Av. de Rebais', ' 77260 La Ferté-sous-Jouarre', ' France']
['Location de salles Le Val Sarah', ' 376 Beaulieu', ' 76480 Bardouville', ' France']
['Berfin Réception', ' 18 Rue Edouard Aubert', ' 91700 Fleury-Mérogis', ' France']
['The House Plenitude', ' Zone Artisanale La Barthaliere', " 84800 L'Isle-sur-la-Sorgue", ' France']
['Domaine de la Rigalière', ' 48 Le Plessis Salo', " 85310 Rives de l'Yon", ' France']
['Salle la perle Sarcelles', ' 12 place de France', ' 95200 Sarcelles', ' France']
['Le Trèfle Orangerie', ' Rte de Dourdan', ' 78730 Sainte-Mesme', ' France']
['Ulysse Salles', ' 11 Av. Clément Ader', ' 77610 Fontenay-Trésigny', ' France']
['BARN GALLERY SPACE', ' 24 Rue de Chevreuse', ' 78720 Dampierre-en-Yvelines', ' France']
['Mise en Seine - Salle de Réception en Normandie', " Parc d'activité de la peupleraie", ' 76490', ' France']
['Salle de Réception Le Prestige', ' 9 Rue Charles François Daubigny', ' 95870 Bezons', ' France']
['La Palmeraie', ' 20 Rue du Colonel Pierre Avia', ' 75015 Paris', ' France']
["Event'3 Salle de réception", ' 23 Gd Rue de Villemeuneux', ' 77170 Brie-Comte-Robert', ' France']
['La Tonnelle', ' 12 Rue Victor Hugo', ' 95200 Sarcelles', ' France']
['La Grange de Montmartre', ' 4 bis Rue de Meaux', ' 60810 Barbery', ' France']
['Auberge du Port', ' 14 Quai Boubou Dado', ' 78780 Maurecourt', ' France']
['Green Diamond', ' 56 Rue Clément et Lucien Matheron', ' 95190 Goussainville', ' France']
['Domaine Fon de Rey', ' Av. de Pézenas', ' 34810 Pomérols', ' France']
['Chateau de Bourguignon', ' Château de bourguignon', ' Rue de Montereau', ' 77370 Fontains', ' France']
['Château de Beaulieu sur Seine - Trévisan Sylvain', ' 1462 Rue de Seine', ' 77350 Boissise-la-Bertrand', ' France']
['Le Prieuré De Vernelle', ' Le Prieuré de Vernelle', " Rte d'Évry", ' 77166', ' France']
['The Stable of Véronge', ' Étable de Véronge', ' 4', ' 77320 La Chapelle-Moutils', ' France']
['Loft Privé', ' Porte Vitrée Centrale', ' 14 bis Rue du Dr Gosselin', ' 94230 Cachan', ' France']
['Le Clos Magnitot', ' Hameau de Magnitot', ' 1 rue du Prieuré', ' 95420 Saint-Gervais', ' France']
['Salle de Réception', ' Séminaire', ' Mariage Val de Marne 94 - Salle C Royal', ' 23 Rue Léon Geffroy', ' 94400 Vitry-sur-Seine', ' France']
['Le Diamant 91', ' 01 Rue Henri Dunant', ' 91800 Bondoufle', ' France']
['Pavillon Dauphine', ' Pl. du Maréchal de Lattre de Tassigny', ' 75116 Paris', ' France']
['Le Bon Temps', ' 20 Av. du Bosquet', ' 95560 Baillet-en-France', ' France']
['L’Apolline', ' 483 Av. de Sainte-Apolline', ' 78370 Plaisir', ' France']
['Pépic salle de réception', ' 75 Rue des Chardonnerets', ' 77340 Pontault-Combault', ' France']
['Bona Venture - Domaine des Aulnaies', ' 25 Rue des Moulins', ' 95510 Amenucourt', ' France']
['La Mavelynière', ' 17 Rue du Village', ' 28300 Poisvilliers', ' France']
['Château de la Présidente : location de salle', ' réceptions', ' mariages', ' Château de la présidente route Toulon', ' D43', ' 83170 Brignoles', ' France']
['Salon Gala', ' 8 Rue Fernand Léger', ' 95480 Pierrelaye', ' France']
["L'olivier", ' 10 Av. Ferdinand de Lesseps', ' 91420 Morangis', ' France']
['Salon Malar', ' 5 Rue Eugène Freyssinet', ' 77270 Villeparisis', ' France']
['La Ferme Champêtre des Carneaux', ' 43 Rue François Mauriac', ' 95470 Vémars', ' France']
['L’instant Gourmand - Salle de Réception avec parc', ' L’instant Gourmand', ' 271 Chau. Jules César', ' 95250 Beauchamp', ' France']
['El Dorado Palace', ' 120 Rue des Madeleines', ' 77100 Mareuil-lès-Meaux', ' France']
['Salle des fêtes Pierre Mendès-France', ' 7 Rue Louis Aragon', ' 60600 Fitz-James', ' France']
['La Grange aux Boeufs', ' Hameau de Givry', ' 8 Imp. de Givry', ' 77970 Pécy', ' France']
['Espace Nova', ' 8 Rue Fernand Léger', ' 95220 Pierrelaye', ' France']
['Vogue Events', ' 3 Av. des Chaumes', ' 78180 Montigny-le-Bretonneux', ' France']
["L'Orée du Stade", ' 20 Rue Génin', ' 93200 Saint-Denis', ' France']
['Location de salle à Paris - Les Salons Parisiens', ' 12 Rue La Fayette', ' 75009 Paris', ' France']
['Palais des Roses - Sasu Traiteur Sassi', ' 328 Rue de Flins', ' 78410 Bouafle', ' France']
['Ferme du soleil', ' ferme du soleil', ' 91710 Vert-le-Petit', ' France']
['Le Moulin De La Maltorne', ' 1 Chem. des Bergeries', ' 78125 Mittainville', ' France']
['Park Plazza', ' 43 Rue Saint-André', ' 93000 Bobigny', ' France']
["FERME du GRAND HOTEL du BOIS Location chambres d'hôtes salle mariage proche Disneyland Paris Marne La Vallée Seine-et-Marne", ' Ferme du Grand Hôtel du Bois', ' 77640 Jouarre', ' France']
['Le Pavillon Passy', ' 6 Rue Faustin Hélie', ' 75116 Paris', ' France']
['1001 Salles - Prestataires événementiels', ' 11 Rue Maurice Grandcoing', ' 94200 Ivry-sur-Seine', ' France']
["Le Paradis d'Anjelina", ' 12 Av. de Paris', ' 91790 Boissy-sous-Saint-Yon', ' France']
['Gentleman de l’événementiel', ' Zi du paradis', ' 60240 Bouconvillers', ' France']
['DOR', ' 8 Rue de la Longueraie', ' 91270 Vigneux-sur-Seine', ' France']
['La Grange du Tertre', " 4 Rue de l'Église", ' 77930 Chailly-en-Bière', ' France']
['Les Jardins du Mas', ' Mas Sisqueilles Lieu Dit La Salut', ' 66380 Pia', ' France']
['Chateau Hermitage De Combas', ' Chateau Hermitage de Combas', ' 34290 Servian', ' France']
['Le Moulin des Noues', ' 8 Rue du Moulin des Noués', ' 91840 Soisy-sur-École', ' France']
['Baccara', ' 61 Rue Saint-André', ' 93000 Bobigny', ' France']
['Le Pavillon Des Princes', " 69 Av. de la Prte d'Auteuil", ' 75016 Paris', ' France']
['STUDIO JENNY', ' 1 Av. Jenny', ' 92000 Nanterre', ' France']
['Domaines & événements', ' 24 Rue du Gouverneur Général Éboué', ' 92130 Issy-les-Moulineaux', ' France']
['Le Cristal', ' 4 Av. des Entrepreneurs', ' 95400 Villiers-le-Bel', ' France']
['Salle des fêtes de Crépy-en-Valois', ' 25 Rue nationale', ' 60800 Crépy-en-Valois', ' France']
['Château de Fleury-la-Forêt', ' 4 Rte de Lyons', ' 27480 Fleury-la-Forêt', ' France']
['Le Domaine du Plessis Luzarches', ' 4 Rue du Moulin', ' 95270 Le Plessis-Luzarches', ' France']
["Le Pavillon d'Elsa", ' 17 Rue de la Mare Poissy', ' 95380 Villeron', ' France']
['Le Diadème Lisses', ' 22 Rue du Bel air', ' 91090 Lisses', ' France']
['Ferme de la Corde', ' 8 Rue de Saint-Julien', ' 77150 Férolles-Attilly', ' France']
['Salle des mariages - Salle de la Charte', ' Bd Résistance et Déportation', ' 49100 Angers', ' France']
['Salle Robillard', ' Rue de Robillard', ' Le Châtelet-en-Brie', ' France', ' 77820 Le Châtelet-en-Brie', ' France']
['The Place Rooftop', ' 58 Rue Bernard', ' 93000 Bobigny', ' France']
["Art D'oise Salon Organization Event Marriage Team Building Room Rental Seminar Catering 60 Saint-Maximin", ' 5 Rue Marie Curie', ' 60740 Saint-Maximin', ' France']
['Salon du Mariage et des évènements de Coulommiers', ' 77 Rue du Général Leclerc', ' 77120 Coulommiers', ' France']
['Salle Dream Herblay', ' 423 Rue de Conflans', ' 95220 Herblay-sur-Seine', ' France']
['Salle l’esterel', ' 5 Rue Antoine-Laurent de Lavoisier', ' 60550 Verneuil-en-Halatte', ' France']
['View Seine - H10 Rentals', ' Hangar', ' 10 Quai Ferdinand de Lesseps', ' 76000 Rouen', ' France']

In [14]:
# Define clean_address with handling for non-string values
def clean_address(address):
    if isinstance(address, str):  # Ensure the input is a string
        address = address.split(',')
        if len(address) > 3:
            address = address[-3:]
        return ','.join(address)  # Rejoin the cleaned parts
    else:
        return None  # Return None for invalid or missing

In [16]:
new_df.shape

(1480, 4)

In [18]:
#new_df['clean_address'] = new_df['address_full'].apply(clean_address)
new_df['clean_address'] = new_df['address_full'].apply(clean_address)

In [19]:
new_df

,name,address_full,phone_number,rating,clean_address
0,Code-Cuisine Le Traiteur Grand-Est,"58 Rue du Bearn, 54400 Cosnes-et-Romain, France",+33 3 57 10 01 14,4.9,"58 Rue du Bearn, 54400 Cosnes-et-Romain, France"
3,Un Chef à la maison ! David Ciré TRAITEUR,"3 Impasse De Hayes, 57640 Vry, France",+33 6 10 11 75 51,4.9,"3 Impasse De Hayes, 57640 Vry, France"
4,Espace Traiteur,"8 Rue Émile Gallé, 54940 Belleville, France",+33 6 13 66 88 56,4.9,"8 Rue Émile Gallé, 54940 Belleville, France"
5,le Traiteur Pierre Mayer et Nisse,"3 Pl. du Marché au Blé, 57220 Boulay-Moselle, ...",+33 7 82 15 33 00,4.9,"3 Pl. du Marché au Blé, 57220 Boulay-Moselle, ..."
10,Le Relais Gourmand,"13 Rue de la Moselotte, 54520 Laxou, France",+33 3 83 21 79 53,4.8,"13 Rue de la Moselotte, 54520 Laxou, France"
...,...,...,...,...,...
2487,Les Traiteurs du Loch,"Lann Guinet, 56390 Grand-Champ, France",+33 2 97 66 77 14,"4,5","Lann Guinet, 56390 Grand-Champ, France"
2492,Traiteur haut de gamme Tours | Frédeville,"Le Boulay, 37270 Saint-Martin-le-Beau, France",+33 2 47 50 27 07,"4,9","Le Boulay, 37270 Saint-Martin-le-Beau, France"
2493,LA CABANE CREOLE TRAITEUR ÉVÉNEMENT ANNIVERSAIRE,"88 Quai de la Fosse, 44100 Nantes, France",+33 7 82 26 79 47,"3,2","88 Quai de la Fosse, 44100 Nantes, France"
2500,Restaurant Traiteur les Terrasses de Bel-Air,"6 Bel air, 44150 Vair-sur-Loire, France",+33 2 40 83 02 87,"4,6","6 Bel air, 44150 Vair-sur-Loire, France"
2502,Traiteur Leroy,"12 Rue Des Maraichers, 44220 Les Hauts de Couë...",+33 9 70 35 08 31,"1,8","12 Rue Des Maraichers, 44220 Les Hauts de Couë..."

In [20]:
import time

def get_coordinates(address):
    geolocator = Nominatim(user_agent="my_geocoder", timeout=10)  # Timeout de 10 secondes
    try:
        location = geolocator.geocode(address)
        if location:
            return location.latitude, location.longitude
        else:
            return None, None
    except Exception as e:
        print(f"Erreur pour l'adresse '{address}': {e}")
        return None, None

In [21]:
new_df['latitude'], new_df['longitude'] = zip(*new_df['clean_address'].apply(get_coordinates))

In [22]:
new_df.head(20)

,name,address_full,phone_number,rating,clean_address,latitude,longitude
0,Code-Cuisine Le Traiteur Grand-Est,"58 Rue du Bearn, 54400 Cosnes-et-Romain, France",+33 3 57 10 01 14,4.9,"58 Rue du Bearn, 54400 Cosnes-et-Romain, France",49.519116,5.710215
3,Un Chef à la maison ! David Ciré TRAITEUR,"3 Impasse De Hayes, 57640 Vry, France",+33 6 10 11 75 51,4.9,"3 Impasse De Hayes, 57640 Vry, France",49.185813,6.332612
4,Espace Traiteur,"8 Rue Émile Gallé, 54940 Belleville, France",+33 6 13 66 88 56,4.9,"8 Rue Émile Gallé, 54940 Belleville, France",48.817232,6.105730
5,le Traiteur Pierre Mayer et Nisse,"3 Pl. du Marché au Blé, 57220 Boulay-Moselle, ...",+33 7 82 15 33 00,4.9,"3 Pl. du Marché au Blé, 57220 Boulay-Moselle, ...",49.183587,6.495637
10,Le Relais Gourmand,"13 Rue de la Moselotte, 54520 Laxou, France",+33 3 83 21 79 53,4.8,"13 Rue de la Moselotte, 54520 Laxou, France",48.698046,6.124910
11,Sur-Mesure By Vincent Vervisch | Chef À Domici...,"3 Rte de Neuhof, 67400 Illkirch-Graffenstaden,...",+33 6 31 35 47 18,5.0,"3 Rte de Neuhof, 67400 Illkirch-Graffenstaden,...",NaN,NaN
12,MikaZ,"3 Rue des Vosges, 57400 Buhl-Lorraine, France",+33 6 77 17 31 37,4.8,"3 Rue des Vosges, 57400 Buhl-Lorraine, France",48.725998,7.087852
13,Les Gentlemen's évents Traiteur,"15 Rue du Stade, 88560 Saint-Maurice-sur-Mosel...",+33 7 66 68 36 97,4.4,"15 Rue du Stade, 88560 Saint-Maurice-sur-Mosel...",47.854389,6.812536
14,Arpèges et Saveurs Gourmandes du Grand-Est,"Imp. de l'Estournel, 54170 Allain, France",+33 6 12 91 53 21,3.8,"Imp. de l'Estournel, 54170 Allain, France",48.551262,5.895209
15,Vernois Traiteur,"32 Rue nationale, 57420 Verny, France",+33 3 87 52 41 42,4.7,"32 Rue nationale, 57420 Verny, France",49.005746,6.204450
16,Traiteur Da Vinci - Al Bosco,"1 All. de la Cité des Chalets, 57600 Forbach, ...",+33 6 17 75 04 42,4.9,"1 All. de la Cité des Chalets, 57600 Forbach, ...",49.185923,6.868915
17,"Croustillance, traiteur & créateur de saveurs","10 Rue de l'Estrey, 88440 Nomexy, France",+33 6 84 26 45 63,4.8,"10 Rue de l'Estrey, 88440 Nomexy, France",48.309336,6.380931
18,TRESSON TRAITEUR,"Rue de Pont-à-Mousson, 57000 Metz, France",+33 6 13 29 46 88,4.6,"Rue de Pont-à-Mousson, 57000 Metz, France",49.105924,6.164017
19,Le Goût et Vous,"52 Rue du Plan Incliné, 57405 Arzviller, France",+33 3 87 23 05 48,4.6,"52 Rue du Plan Incliné, 57405 Arzviller, France",48.720602,7.167511
20,DAN traiteur,"51b Rue de la Potence, 57360 Amnéville, France",+33 6 16 04 42 21,4.9,"51b Rue de la Potence, 57360 Amnéville, France",49.218872,6.065308
21,Cuisto 57,"68 Rue Principale, 57550 Falck, France",+33 6 80 37 99 18,4.6,"68 Rue Principale, 57550 Falck, France",49.232524,6.635842
23,Le Mât de Cocagne Traiteur,"4 All. de l'Europe, 67140 Barr, France",+33 3 88 58 89 22,4.6,"4 All. de l'Europe, 67140 Barr, France",NaN,NaN
26,Sam Régale Les Papilles,"9 Rue de Willermont, 54540 Pexonne, France",+33 6 20 08 62 66,5.0,"9 Rue de Willermont, 54540 Pexonne, France",48.484452,6.868531
27,La Toque Mosellane Traiteur,"99 Rue Principale, 57980 Diebling, France",+33 3 87 02 82 32,4.5,"99 Rue Principale, 57980 Diebling, France",49.111930,6.933646
28,EMD Traiteur,"5 Rue Haie le Bailly, 57530 Silly-sur-Nied, Fr...",+33 3 87 64 06 26,4.9,"5 Rue Haie le Bailly, 57530 Silly-sur-Nied, Fr...",49.120861,6.356170

In [23]:
new_df.isna().mean()

name             0.000000
address_full     0.000000
phone_number     0.000000
rating           0.000000
clean_address    0.000000
latitude         0.216216
longitude        0.216216
dtype: float64

In [24]:
new_df = new_df.dropna()
new_df.shape

(1160, 7)

In [27]:
# select the 400 first exemples
new_df = new_df.head(400)
new_df.shape

(400, 7)

In [28]:
new_df.to_csv('cleaned_data_traiteur.csv', index=False)

In [30]:
get_coordinates("15 rue Génin 93200 Saint-Denis France")

(48.929305, 2.354483)

In [31]:
names = new_df['name'].tolist()
names

['factory 58',
 'Espace Venise',
 'Glassy Events',
 'Salle de réception Le Vendome',
 'Farm Petite Loge',
 'Espace Eden | Salle de Réception 77 | Salle de réception seine et marne',
 'Chateau de Serans',
 'Domaine La Bastide',
 'Espace Royal - Salles de Reception',
 'factory 58',
 'Palais Groupe Salle de Mariage 91',
 'Domaine de la Butte Ronde',
 'La Ferme Du Parc',
 'Castle Vaugrigneuse',
 'La Verrière 91',
 "LE CLOS DE L'ORANGERIE",
 'Domaine du Chateau Verderonne',
 'Reception room THE TULIPS',
 'Le Carré Marne',
 'RITZ PLAZZA',
 'Manoir De La Chapelle Room Receptions Hotel',
 'Château de Saint-Martin-du-Tertre',
 'The Golden Edge',
 'Orangerie du Manoir des Vignes',
 'Le Joyau de la Marne',
 'La Bella - Wedding Room, Reception',
 "Le palmier d'or 77 - Location salle de réception mariage traiteur à domicile SEINE-ET-MARNE 77",
 'Area Des Clos Vallées Salle De Réceptions',
 'Villiers Palace mariage',
 "Loca'Salle",
 'Palais 77 | Salle de Mariage',
 'Salle de réception Espace La Palombe',
 'La Ferme du Roy',
 'Ferme Du Prieuré',
 'Salle de Réception Mariage Rhône Alpes - Le Château du Sou',
 'Domaine des Coccinelles',
 'LOKUS l SALLE DE RECEPTIONS 77',
 'Le palacio',
 'Domaine de la Nacelle',
 "Salle LUNE D'OR",
 'Le Pavillon de la Marne',
 'Ferme de Beauvais',
 'Domaine De La Vallée Aux Pages',
 'Pavillon Royal',
 'Salle Mélodie',
 'Victoria Park',
 'Ferme du silo - Location de salle réception (Seine et Marne)',
 'Location de salle, salle de mariage, Royal Riaz 77',
 'La Bella Vita',
 'Cristal 91',
 'Moulin de Moulignon',
 'La Rose 77 | Événementiel (77)',
 'Le Manoir Du Thil',
 'Ferme du Genièvre',
 'FOREST FARM',
 'Château de Lésigny',
 'The Royal Wedding',
 'THE ROOM FAUVETTES',
 'The Fiesta & Privilege - Receptions',
 'La Bella Argenteuil',
 'La Scena',
 'Royal Plaza',
 'Golden House Salle des Fêtes',
 'Salle De Récéption Ile De France -La Grand Maison- Salle Mariage-Location De Salle Ile De France',
 'Location salle 91 - Bondoufle Réception - Palace Event',
 'Le Jardin D’alya',
 'Château Mariage Oise "Domaine de Sainte Claire',
 "Mary d'Arvigny",
 'La ferme de Vintué',
 'Le Château de Nans',
 'La Girafe paris réceptions',
 'Castle Santeny',
 'Le Manège de Saint Cloud',
 'Espace Noisy Le Sec',
 "Chateau d'Amécourt:Séminaire réunion salle mariage réception location château gite de groupe Eure",
 "Le Domaine d'Euclide",
 'Orchidée',
 "château de Saint Offenge - Mariages, Séminaires, Maison d'Hôtes",
 'Château Bouffémont',
 'Field La Mazure',
 'Manoir De Randrecard',
 'Les Salons Emirates',
 'Area Des Bayettes',
 'Les Salons Beauchamp',
 'Le Paradise 77 | salle de réception 77 | salle de mariage Meaux 77',
 'Field The Edge Of The Bois',
 'Chateau de Plumasserie',
 'Area Du Bois Saint Mard',
 'Salons Varenne',
 'La Méridienne',
 'The Manor of My Father',
 'Le domaine du Ruisseau',
 'Salle Le Diamant',
 'Le Colombier du Manoir',
 'La Closerie de Montgermont',
 'Le Saphir',
 'Salon La Belle Alliance',
 'Manoir de Tigeaux',
 'domaine des 3 voyages',
 'Sen Sabai Salle de Réception',
 'Les Salons Hoche',
 'The Marolles Garden',
 'Domaine du Petit Varennes',
 'Salle Neila Maya',
 'Le Corps de Garde: location salle de réception, mariages, séminaire, cérémonie laïque (Oise 60)',
 'Salle de Réception Matecaña',
 'le Moulin de Mourette',
 'Berfin Réception',
 'Domaine de la Rigalière',
 'Salle la perle Sarcelles',
 'Le Trèfle Orangerie',
 'Ulysse Salles',
 'Salle de Réception Le Prestige',
 'La Palmeraie',
 'La Tonnelle',
 'La Grange de Montmartre',
 'Auberge du Port',
 'Green Diamond',
 'Domaine Fon de Rey',
 'Chateau de Bourguignon',
 'Château de Beaulieu sur Seine - Trévisan Sylvain',
 'Le Prieuré De Vernelle',
 'The Stable of Véronge',
 'Domaine du patis',
 'Le Clos Magnitot',
 'Salle de Réception, Séminaire, Mariage Val de Marne 94 - Salle C Royal',
 'Le Diamant 91',
 'Pavillon Dauphine',
 'Le Bon Temps',
 'L’Apolline',
 'Pépic salle de réception',
 'Bona Venture - Domaine des Aulnaies',
 'La Mavelynière',
 'Château de la Présidente : location de salle, réceptions, mariages',
 'Salon Gala',
 "L'olivier",
 'Salon Malar',
 'La Ferme Champêtre des Carneaux',
 'El Dorado Palace',
 'Salle des fêtes Pierre Mendès-France',
 'La Grange aux Boeufs',
 'Espace Nova',
 'Vogue Events',
 "L'Orée du Stade",
 'Location de salle à Paris - Les Salons Parisiens',
 'Palais des Roses - Sasu Traiteur Sassi',
 'Park Plazza',
 'Le Pavillon Passy',
 '1001 Salles - Prestataires événementiels',
 "Le Paradis d'Anjelina",
 'DOR',
 'La Grange du Tertre',
 'Chateau Hermitage De Combas',
 'Le Moulin des Noues',
 'Baccara',
 'STUDIO JENNY',
 'Domaines & événements',
 'Le Cristal',
 'Salle des fêtes de Crépy-en-Valois',
 'Château de Fleury-la-Forêt',
 'Le Domaine du Plessis Luzarches',
 "Le Pavillon d'Elsa",
 'Le Diadème Lisses',
 'Salle des mariages - Salle de la Charte',
 'The Place Rooftop',
 "Art D'oise Salon Organization Event Marriage Team Building Room Rental Seminar Catering 60 Saint-Maximin",
 'Salon du Mariage et des évènements de Coulommiers',
 'Salle Dream Herblay',
 'Salle l’esterel',
 'View Seine - H10 Rentals',
 'Cellier Saint Paul',
 'Biotiful Traiteur / Salle de réception',
 "La Ferme de l'Avenir",
 'Mission Mariage',
 'Fête In France',
 'Salle des Fêtes',
 'La Verrière Insolite',
 'Une Salle A Paris (location salle paris, privatisation salle paris)',
 'Location de salle de réception à Paris',
 'Dom Traiteur Ile De France - Traiteur 77',
 'Wedding in the Air',
 'Great Weddings in France']

In [34]:
def convertir_en_entier(s):
    # Remplacer les virgules par des points
    s = s.replace(',', '.')

    # Convertir en flottant
    nombre_flottant = float(s)

    # Convertir en entier (arrondi vers le bas)
    nombre_entier = int(nombre_flottant)

    return nombre_entier

In [36]:
convertir_en_entier('4,5')*' *'

' * * * *'