In [10]:
import pandas as pd

def load_df(filepath="data/fleuriste.csv"):
    print(f"File path : {filepath}")
    try:
        # On essaie d'accéder à la variable 'location_path' dans le module 'paths'
        file_path = filepath

        # Lecture du fichier CSV
        df_location = pd.read_csv(file_path)

    except AttributeError:
        print("Le chemin du fichier est introuvable.")
    except FileNotFoundError:
        print("Le fichier spécifié est introuvable.")
    return df_location

In [11]:
df = load_df()
df.head()

File path : data/fleuriste.csv

,Name,Address_full,Phone_number,Website,Region,longitude,latitude,result_score,result_score_next,result_label,...,result_name,result_street,result_postcode,result_city,result_context,result_citycode,result_oldcitycode,result_oldcity,result_district,result_status
0,FLOWERS OF A NEW WORLD,NaN,+33 9 83 35 90 51,https://www.fleursmariage.com/,Provence Alpes Côte d'Azur,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,not-found
1,Les Brindilles d'Or,NaN,+33 7 86 87 43 33,https://www.lesbrindillesdor.com/,Provence Alpes Côte d'Azur,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,not-found
2,Man-fado,NaN,+33 6 75 32 12 01,https://www.man-fado.com/,Provence Alpes Côte d'Azur,0.214982,48.011388,0.145913,NaN,Impasse Saint Côme 72000 Le Mans,...,Impasse Saint Côme,Impasse Saint Côme,72000.0,Le Mans,"72, Sarthe, Pays de la Loire",72181,NaN,Le Mans,NaN,ok
3,Éleen : Fleuriste & Décoratrice d'évènements e...,NaN,+33 6 14 55 22 86,https://www.eleen.fr/,Provence Alpes Côte d'Azur,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,not-found
4,T amo eventi,NaN,+33 6 31 09 46 45,https://www.t-amoeventi.fr/,Provence Alpes Côte d'Azur,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,not-found

In [12]:
df.columns = df.columns.str.lower()
df.head()

,name,address_full,phone_number,website,region,longitude,latitude,result_score,result_score_next,result_label,...,result_name,result_street,result_postcode,result_city,result_context,result_citycode,result_oldcitycode,result_oldcity,result_district,result_status
0,FLOWERS OF A NEW WORLD,NaN,+33 9 83 35 90 51,https://www.fleursmariage.com/,Provence Alpes Côte d'Azur,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,not-found
1,Les Brindilles d'Or,NaN,+33 7 86 87 43 33,https://www.lesbrindillesdor.com/,Provence Alpes Côte d'Azur,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,not-found
2,Man-fado,NaN,+33 6 75 32 12 01,https://www.man-fado.com/,Provence Alpes Côte d'Azur,0.214982,48.011388,0.145913,NaN,Impasse Saint Côme 72000 Le Mans,...,Impasse Saint Côme,Impasse Saint Côme,72000.0,Le Mans,"72, Sarthe, Pays de la Loire",72181,NaN,Le Mans,NaN,ok
3,Éleen : Fleuriste & Décoratrice d'évènements e...,NaN,+33 6 14 55 22 86,https://www.eleen.fr/,Provence Alpes Côte d'Azur,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,not-found
4,T amo eventi,NaN,+33 6 31 09 46 45,https://www.t-amoeventi.fr/,Provence Alpes Côte d'Azur,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,not-found

In [14]:
selected_columns = ['name', 'address_full', 'phone_number', 'latitude', 'longitude']
#selected_columns = ['name'.upper(), 'address_full'.upper(), 'phone_number'.upper(), 'rating'.upper()]
new_df = df[selected_columns]
new_df.isna().mean()

name            0.000000
address_full    0.225368
phone_number    0.049830
latitude        0.238392
longitude       0.238392
dtype: float64

In [15]:
new_df = new_df.dropna()

In [7]:
new_df.isna().mean()

name            0.0
address_full    0.0
phone_number    0.0
rating          0.0
latitude        0.0
longitude       0.0
dtype: float64

In [16]:
new_df.shape

(1142, 5)

In [17]:
df.to_csv("preprocessed_data/fleuriste.csv", index=False)